version: '3.1'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - '5432:5432'
  redis:
    image: redis:alpine
    ports:
     - '6379:6379'
