name: Build

env:
  REGISTRY: ghcr.io

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        package:
          - crates/backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: package-name
        uses: actions/github-script@0.9.0
        env:
          MATRIX_PACKAGE: ${{ matrix.package }}
        with:
          script: |
            const package = process.env.MATRIX_PACKAGE.split('/')[1]
            core.setOutput('package', package)
      
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-${{ steps.package-name.outputs.package }}
          flavor: |
            latest=false
          tags: |
            type=edge,value=edge
            type=ref,event=pr
            type=sha
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ${{ matrix.package }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max